import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cookie Policy — ShieldCaptcha Enterprise",
  description: "ShieldCaptcha uses zero tracking cookies. This page explains what cookies are used and why.",
};

export default function CookiesPage() {
  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-4xl mx-auto px-6 py-16 w-full">
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 border border-indigo-100 text-indigo-700 text-xs font-semibold mb-4">
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-500" />
            Legal Document
          </div>
          <h1 className="text-3xl font-extrabold text-slate-900 mb-3">Cookie Policy</h1>
          <p className="text-slate-500 text-sm">
            <strong>Last updated:</strong> October 4, 2026
          </p>
        </div>

        <div className="space-y-10 text-sm text-slate-700 leading-relaxed">

          {/* TL;DR banner */}
          <div className="p-5 rounded-2xl bg-emerald-50 border border-emerald-200 flex gap-4 items-start">
            <span className="text-2xl">🍪</span>
            <div>
              <h2 className="font-bold text-emerald-900 text-base mb-1">Short Answer: No Tracking Cookies</h2>
              <p className="text-emerald-800 text-sm">
                ShieldCaptcha does <strong>not</strong> use advertising cookies, analytics cookies, or any
                cross-site tracking technology. The verification process is fully stateless from a cookie
                perspective.
              </p>
            </div>
          </div>

          <section>
            <h2 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2 mb-4">What Is a Cookie?</h2>
            <p>
              A cookie is a small text file stored in your browser by a website. Cookies are used for a wide
              range of purposes: keeping you logged in, remembering preferences, or — in many cases — tracking
              your behaviour across websites for advertising.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2 mb-4">Cookies Used by ShieldCaptcha</h2>
            <div className="overflow-x-auto">
              <table className="w-full text-xs border-collapse">
                <thead>
                  <tr className="bg-slate-100">
                    <th className="text-left px-3 py-2 font-semibold text-slate-700 border border-slate-200">Cookie</th>
                    <th className="text-left px-3 py-2 font-semibold text-slate-700 border border-slate-200">Type</th>
                    <th className="text-left px-3 py-2 font-semibold text-slate-700 border border-slate-200">Purpose</th>
                    <th className="text-left px-3 py-2 font-semibold text-slate-700 border border-slate-200">Duration</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="px-3 py-2 border border-slate-200 font-mono text-slate-800 text-[11px]">None</td>
                    <td className="px-3 py-2 border border-slate-200">
                      <span className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 font-semibold text-[10px]">None</span>
                    </td>
                    <td className="px-3 py-2 border border-slate-200 text-slate-600">ShieldCaptcha does not set any cookies</td>
                    <td className="px-3 py-2 border border-slate-200 text-slate-600">N/A</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p className="mt-3 text-slate-500 text-xs">
              The verification token generated by ShieldCaptcha is passed as a hidden form field or via
              JavaScript callback — it is <strong>never written to <code>document.cookie</code></strong>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2 mb-4">This Website (Portal)</h2>
            <p>
              This documentation portal may set a single <strong>functional session cookie</strong> if you
              access authenticated features (e.g., live API testing). It is:
            </p>
            <ul className="mt-3 space-y-2 list-disc list-inside text-slate-600">
              <li>Strictly necessary for the feature to work</li>
              <li>Not shared with any third party</li>
              <li>Session-scoped: deleted when you close your browser</li>
              <li>Contains no personally identifiable information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2 mb-4">Third-Party Services</h2>
            <p>
              This portal does not embed:
            </p>
            <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-2">
              {[
                "Google Analytics",
                "Meta Pixel / Facebook Tracking",
                "Twitter/X pixel",
                "HotJar or FullStory",
                "Google Ads / AdSense",
                "Any CDN-hosted font trackers",
              ].map(item => (
                <div key={item} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-slate-50 border border-slate-200 text-slate-700 text-xs">
                  <span className="text-emerald-600 font-bold">✓</span> Not used: {item}
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2 mb-4">Managing Cookies</h2>
            <p>
              Since ShieldCaptcha sets no cookies, there is nothing to manage or opt out of. If you use a
              browser extension that blocks all cookies (e.g., uBlock Origin), ShieldCaptcha will continue
              to function normally.
            </p>
            <p className="mt-2">
              To manage cookies set by your browser generally, visit your browser settings:
            </p>
            <ul className="mt-3 space-y-1 list-disc list-inside text-slate-600">
              <li><strong>Chrome:</strong> Settings → Privacy and security → Cookies and other site data</li>
              <li><strong>Firefox:</strong> Settings → Privacy & Security → Cookies and Site Data</li>
              <li><strong>Safari:</strong> Preferences → Privacy → Manage Website Data</li>
              <li><strong>Edge:</strong> Settings → Cookies and site permissions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-slate-900 border-b border-slate-100 pb-2 mb-4">Contact</h2>
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-sm">
              Cookie questions: <a href="mailto:privacy@shieldcaptcha.dev" className="text-indigo-600 hover:underline">privacy@shieldcaptcha.dev</a>
            </div>
          </section>

        </div>
      </main>
      <Footer />
    </div>
  );
}
